### ISSUE TITLE
Convoy teleports when first loaded up

### ISSUE THREAD

**Issue by cyberredcoat** [Darr3n2GG/Snake-GameJam-2024-CLHS#22]
When loaded, the Convoy spawns at the top left then teleports to the middle

**Comment by cyberredcoat** [comment]
Patched

**Comment by Darr3n2GG** [comment]
fixed in commit [b1e50fb](https://github.com/Darr3n2GG/Snake-GameJam-2024-CLHS/commit/b1e50fb5fb6c1cd225ab79a40f7e47a6a3190fe0)
